### ISSUE TITLE
F-Droidへのapkのアップロード

### ISSUE THREAD

**Issue by eniehack** [pantasystem/MisskeyAndroidClient#1]
## 概要
F-Droidにapkをアップロードすることによりダウンロードやアップデートが簡単なものとなり、多くのユーザに使ってもらえるものと思います。やや手続きが面倒なように感じますが……。

## 要件
- [ ] https://gitlab.com/fdroid/rfp/-/blob/master/README.md#submission-queue にある5つの要件を満たす
- [ ] [F-DroidのInclusion Policy](https://f-droid.org/docs/Inclusion_Policy/?title=Inclusion_Policy)を満たす(以下意訳なので参考程度に読んでください) 
  - [x] フリーソフトウェア(OSS)であること → [GPL-v3](https://github.com/Kinoshita0623/MisskeyAndroidClient/blob/master/LICENSE)
  * 必須条件(Notably)
    - [ ] Google Play Servicesを使っていないこと。
    - [ ] プロプライエリなトラッキング、分析ツールが依存関係に含まれないこと。
      * Crashlytics、Firebaseなど
    - [ ] プロプライエタリな広告ライブラリを使っていないこと。
    - [ ] Oracle JDKなどの、Non-Freeなビルドツールを用いないこと。
  * 追加条件(Additionally)
    - [x] 誰にでもアクセス可能なバージョン管理システム(git, Mercurial, Subversion, Bazaarのうちいづれか)で管理されていること(must)。→ GitHubにて公開リポジトリで開発されている
    - [ ] 追加の実行可能なバイナリファイルをダウンロードしないこと(should)
      * 例: Non-FreeなAddonや自動更新
    - [ ] 一意なAndroid package IDを持っていること(should)。
    - [ ] トレードマークを侵害してはならない(must)。また、他の法的要件を遵守しなければならない(must)。
    - [ ] Although not ideal, “non-functional” assets (e.g. artwork) may be acceptable under less permissive licenses than functional code - an example would be artwork assets that are licensed only for use with that particular game. In any case though, they must be included under some kind of license, and not be copyright. (原文ママ)
    - [ ] F-Droid does not sign up for any API keys. Even if provided by a third party, we include them in both, binary and sourcecode releases. (原文ママ)
    - [ ] .jarのようなバイナリの依存関係はsource-built versionsに置換するか trusted repositoryから使用しなければならない(have to)。
  * 理想(Ideally)
    - [ ] リリースは明確にタグ付けまたはマークされる必要がある
- [ ] https://gitlab.com/fdroid/rfp/-/issues にRequestを立てる

また、参考リンクにも含めておきましたが、[Inclusion How To](https://f-droid.org/docs/Inclusion_How-To/)はF-Droidに追加されるまでの流れが書いてありますので、F-Droidに申請する場合は一読するべきかと思います。参考までに。

以上、よろしくお願いします。

## 参考リンク

* [README.md · master · F-Droid / Requests For Packaging · GitLab](https://gitlab.com/fdroid/rfp/-/blob/master/README.md#submission-queue)
* [Inclusion Policy | F-Droid](https://f-droid.org/docs/Inclusion_Policy/?title=Inclusion_Policy)
* [Inclusion How-To | F-Droid](https://f-droid.org/docs/Inclusion_How-To/)
* [プロプライエタリ・ソフトウェア - Wikipedia(ja)](https://ja.wikipedia.org/wiki/%E3%83%97%E3%83%AD%E3%83%97%E3%83%A9%E3%82%A4%E3%82%A8%E3%82%BF%E3%83%AA%E3%83%BB%E3%82%BD%E3%83%95%E3%83%88%E3%82%A6%E3%82%A7%E3%82%A2)

**Comment by Kinoshita0623** [comment]
感謝します。
認証関連の問題を解決次第検討します。
