### ISSUE TITLE
ギャラリーの実装

### ISSUE THREAD

**Issue by pantasystem** [pantasystem/MisskeyAndroidClient#152]
https://github.com/misskey-dev/misskey/releases/tag/12.75.0
12.75.0(たぶん)でギャラリー機能が追加されているので実装すること。
また以下のことを調査してから実装すること。
- [x] 本当に12.75.0か？
- [x] パーミッションは追加で必要なのか

**Comment by Kinoshita0623** [comment]
- [ ] ユーザー詳細画面からユーザーのギャラリー投稿をタブにピン止めできるようにする
- [ ] ギャラリー専用の画面を作成する
- [ ] ギャラリーの詳細画面を作成する
    - [ ] ユーザーの情報
    - [ ] 投稿された全画像
    - [ ] タイトル
    - [ ] 説明文
- [ ] ギャラリーの作成＆編集画面を作成する
- [ ] MainActivityのfabを上位Fragmentのアクションによって切り替えられるようにする

**Comment by Kinoshita0623** [comment]
## 詳細画面について
画像を縦スクロールで表示できるようにする。
その下にタイトル
デスクリプション
ユーザー情報
アクションを表示する

**Comment by Kinoshita0623** [comment]
ギャラリーは一覧画面の時点で横スワイプ可能にした。
- [ ] 一覧画面の画像にドットタブを表示し横スワイプ可能であることを表す
- [ ] 親Pagerに横スワイプイベントを伝えない方法を考える
