### ISSUE TITLE
GalleryPostをComposeに置き換える

### ISSUE THREAD

**Issue by pantasystem** [pantasystem/MisskeyAndroidClient#224]
GalleryPostのCardをComposeに置き換える

**Comment by Kinoshita0623** [comment]
Compose化する対象
GalleryPostCard
GalleryPhotoCompose化する対象
## GalleryPostCard
* GalleryPostのCard
## GalleryPostCardList
* GalleryPostCardのリスト表示
## ThumbnailPreviewHorizontalPager
* ThumbnailPreviewを横スクロールするためのコンポーネント
## ThumbnailPreview
FileProeprtyのmetaに合わせVideoのPreviewとImageのPreviewをいい感じにして表示する

## FavoriteButton
 * いいねの状態を表示&クリックイベントを受けるボタン
