### ISSUE TITLE
投稿フォームのJetpack Compose化の検討

### ISSUE THREAD

**Issue by pantasystem** [pantasystem/MisskeyAndroidClient#279]
Composeの方がコンポーネント化がしやすく
動的で自由なレイアウトが可能と考えられる。
そこでCompose化が可能であるのかを調査＆実装をする。
## 調査すべき前提事項
* Compose化時のメリットの調査
* Compose化の可否
* Compose化する際に変更が必要な点

## 懸念事項
* Composeは単一データフローを前提としている。そのため、FORM特有の複雑な処理をどのように部品化するのか（コールバック関数をどのようにどこに実装する）
* Auto Complete機能がデフォルトではないため自前で実装する必要がある。
* テストの自動化について(この際自動化したい)

**Comment by Kinoshita0623** [comment]
# 必要な機能
## 本文入力
テキストを入力します。
複数行をサポートし、改行をします。
またカスタム絵文字のサジェスチョンをサポートします。

## CW
### CW入力
単一行のテキスト入力。
### CW入力切り替え
CWの有無を切り替えます。

## 投票
### 投票の切り替え
投票の有無を切り替えます。

### 投票候補の追加
テキストの候補を追加します。

### 投票の期限の指定
投票の有効期限を指定します。
また期限の指定は以下の種類から選択できるようにします。
* 経過指定
* 期限日時指定
* 無期限

## ファイルの添付
### ローカルからのファイルの選択
### Driveからのファイル選択
### 選択したファイルのプレビュー
### 選択したファイルのNSFW指定の切り替え
### 選択したファイルの添付解除

## 下書きからの編集
下書きとして保存した投稿をフォームに適応して編集作業を再開する機能。

## 絵文字選択機能
カスタム絵文字を一覧表示して、
カスタム絵文字を選択するとその絵文字を本文入力に挿入する機能。

## 公開範囲選択機能
* public
* local
* followers
* direct

**Comment by Kinoshita0623** [comment]
# カスタム絵文字入力候補表示実装について
DropdownMenuとDropdownMenuItemを使えば実現は可能か？
ただしフォーカスの状態に合わせて表示、非表示を切り替える必要がある
https://stackoverflow.com/questions/67111020/exposed-drop-down-menu-for-jetpack-compose

**Comment by Kinoshita0623** [comment]
# cursorの現在位置の取得方法
メンションを挿入したり絵文字を挿入するときなどに使用することが想定される。
https://developer.android.com/reference/kotlin/androidx/compose/ui/text/input/TextFieldValue

**Comment by Kinoshita0623** [comment]
カスタム絵文字のAuto Completeの実現性の可否で続行するか否かを決定する。

**Comment by Kinoshita0623** [comment]
現在入力しているIMEの値はTextFieldValueのcompositionから取得できるとのこと。

**Comment by pantasystem** [comment]
技術的に現在の操作性を超える実装ができないことがわかったためなし。
