### ISSUE TITLE
Please add compiled apk to the releases

### ISSUE THREAD

**Issue by jahway603** [pantasystem/MisskeyAndroidClient#289]
* Please add compiled apk to the releases
* I do not speak the required language, but I see an apk for just f-droid in issue #1

**Comment by pantasystem** [comment]
That's tough because we need GMS.

**Comment by jahway603** [comment]
What does GMS stand for?

**Comment by pantasystem** [comment]
I made a mistake 
~~GMS~~ Google Play Services

**Comment by Hayao0819** [comment]
I know that #1 has been closed due to the GMS.
But still I think that the issue to update github release and upload apk can be resolved.
