### ISSUE TITLE
翻訳

### ISSUE THREAD

**Issue by HSDChannel** [pantasystem/MisskeyAndroidClient#290]
こんにちは、このアプリはどこで翻訳できますか？

**Comment by pantasystem** [comment]
What do you want to translate?

1. Misskey post(Note)
2. Language of the app

**Comment by HSDChannel** [comment]
Language of the app

**Comment by HSDChannel** [comment]
> What do you want to translate?
> 
> 1. Misskey post(Note)
> 2. Language of the app

Language of the app

**Comment by pantasystem** [comment]
This is English(default) Language file.
https://github.com/pantasystem/MisskeyAndroidClient/blob/develop/app/src/main/res/values/strings.xml

You can request changes by pull request.
