### ISSUE TITLE
can't authenticate

### ISSUE THREAD

**Issue by tnntwister** [pantasystem/MisskeyAndroidClient#294]
Hi, 

I've just installed the app. 
when i'm typing the instance url, the authentication button stays disabled.

An error message printed could be useful :)
![Screenshot (21 nov](https://user-images.githubusercontent.com/40766799/142777485-c8cf43a6-504e-4717-8ea3-c5b56b154bfe.png)

Thanks for having read it in english.

**Comment by pantasystem** [comment]
私の環境ではmisskey.frで認証できることを確認しました。
## 予定する改善策
* エラーが発生した場合、エラーメッセージを表示する
* ローディング状態を表示する
* ログを送信できるようにする
これを予定しています。


I have confirmed that I can authenticate with misskey.fr in my environment.
## Planned improvements.
* Display error message when an error occurs.
* Display the loading status.
* Make it possible to send logs.
This is what we are planning to do.
