### ISSUE TITLE
Problems with the translator in the app

### ISSUE THREAD

**Issue by HSDChannel** [pantasystem/MisskeyAndroidClient#318]
When you click on the "Translate" button, this happens:
![Screenshot_20211207_151311_jp panta misskeyandroidclient](https://user-images.githubusercontent.com/72506029/145006217-ba19d862-8701-4ddb-82c5-662194345866.jpg)

**Comment by pantasystem** [comment]
<en>
- What is the language of your device?
- Do you have problems with other posts as well?
- Are you always having problems?
</en>
<jp>
- 端末の言語は何ですか？
- 他の投稿でも問題は発生していますか？
- 問題は今でも発生していますか？
</jp>

**Comment by HSDChannel** [comment]
> ### English
> * What is the language of your device?
> * Do you have problems with other posts as well?
> * Are you always having problems?
> 
> ### Japanese
> * 端末の言語は何ですか？
> * 他の投稿でも問題は発生していますか？
> * 問題は今でも発生していますか？

>What is the language of your device?
Russian
>Do you have problems with other posts as well?
It's the same with the others.
>Are you always having problems?
Yes

**Comment by pantasystem** [comment]
Which instance are you usign?

**Comment by HSDChannel** [comment]
> 

quietplace.xyz

**Comment by pantasystem** [comment]
This instance does not seem to support the translation API.
Contact the operator of the instance for details.

**Comment by HSDChannel** [comment]
> This instance does not seem to support the translation API. Contact the operator of the instance for details.

Okay,
