### ISSUE TITLE
Bugs with the left menu / 左メニューの不具合

### ISSUE THREAD

**Issue by HSDChannel** [pantasystem/MisskeyAndroidClient#337]
![Screenshot_20211221_165522_com huawei himovie overseas](https://user-images.githubusercontent.com/72506029/146944671-a268b674-f823-4d5e-bcda-594296dacbf4.jpg)
![Screenshot_20211221_165550_com huawei himovie overseas](https://user-images.githubusercontent.com/72506029/146944708-803b3575-88a3-49b1-9745-69f90d2c3c70.jpg)

**Comment by pantasystem** [comment]
This bug will be fixed in the next update.
