### ISSUE TITLE
Continuous Build

### ISSUE THREAD

**Issue by z8512** [pantasystem/MisskeyAndroidClient#457]
Can you provide APK binaries using Github Actions of latest commit? Both FCM and non-FCM

**Comment by z8512** [comment]
https://github.com/pantasystem/MisskeyAndroidClient/blob/develop/.github/workflows/main.yml#L38

**Comment by pantasystem** [comment]
Umm...
There are no plans to offer a non-FCM version.
I also don't have any good ideas for implementing notifications without using FCM.

**Comment by pantasystem** [comment]
There are ways to get periodic notifications, but they are inefficient

**Comment by ThatOneCalculator** [comment]
> There are ways to get periodic notifications, but they are inefficient

Even builds without FCM/notifications would be appreciated in Github actions :)

**Comment by ThatOneCalculator** [comment]
CI/CD @pantasystem について何か更新はありますか？最新バージョンに簡単にアクセスできるようにしたいのですが :)

**Comment by pantasystem** [comment]
I am busy.
No knowledge of GitHub Actions.

**Comment by ThatOneCalculator** [comment]
:(
