### ISSUE TITLE
デプロイの自動化(CD)

### ISSUE THREAD

**Issue by pantasystem** [pantasystem/MisskeyAndroidClient#460]
## 何をしたいのか
タグを作成したタイミングでリリースビルドを行い
PlayConsoleへ自動的にデプロイを行いたい。
また変更履歴もいい感じに自動的に更新したい。

**Comment by pantasystem** [comment]
## versionNameをタグから作成
https://damienaicheh.github.io/xamarin/github/actions/2021/07/15/manage-mobile-version-github-actions-en.html

**Comment by pantasystem** [comment]
## versionCodeを自動的に更新
https://github.com/marketplace/actions/increment-the-version-code-of-your-project

**Comment by pantasystem** [comment]
## PlayConsoleへアップロード
https://github.com/marketplace/actions/upload-android-release-to-play-store

**Comment by ThatOneCalculator** [comment]
とりあえず、ビルドの成果物を https://github.com/pantasystem/MisskeyAndroidClient/actions/workflows/main.yml から作ることは可能でしょうか。

![image](https://user-images.githubusercontent.com/44733677/156946239-7dfaf57b-bd9a-424c-9b73-2798a5833e97.png)

**Comment by pantasystem** [comment]
まだできないです。

**Comment by ThatOneCalculator** [comment]
@pantasystem something is wrong with the build process. Did you put your key into secrets?

![Screenshot_20220612-090230.png](https://user-images.githubusercontent.com/44733677/173242170-90392016-71fd-40f9-b32e-3250c7263a90.png)

**Comment by pantasystem** [comment]
What key is it?
