### ISSUE TITLE
Feature: support for "comment" field in image uploads（Driveコメントフィールドを使えるようにする)

### ISSUE THREAD

**Issue by EvelynSubarrow** [pantasystem/MisskeyAndroidClient#516]
Hello!

I'd like to request support for the "comment" field, which seems to be used for image alt-text in misskey. This would allow me to describe the images I upload for blind followers who use screen readers.

https://misskey.io/api-doc#operation/drive/files/create

Thank you

**Comment by pantasystem** [comment]
Hi!
I figured out the issue.
Thank you for creating the issue!

**Comment by pantasystem** [comment]
## 対応方法
### ノート作成画面
- コメント入力、編集用のダイアログを表示できるようにする。

### ドライブアップロード画面
- アップロード時にダイアログを表示して、入力用のTextFieldを表示する

**Comment by EvelynSubarrow** [comment]
Thank you!

**Comment by pantasystem** [comment]
It will be reflected in the next update.
