### ISSUE TITLE
公開範囲をリモートと同期できるようにする

### ISSUE THREAD

**Issue by pantasystem** [pantasystem/MisskeyAndroidClient#69]
リモートとノートの投稿範囲を同期できるようにする。

**Comment by Kinoshita0623** [comment]
エンドポイントapi/i/registryはアクセスしていいAPIかわからないため、保留とする。
[registryのエンドポイントのソースコード](https://github.com/misskey-dev/misskey/blob/develop/src/server/api/endpoints/i/registry/get-all.ts)
