### ISSUE TITLE
私のインスタンスneko.ciはmilkteaでログインできません。

### ISSUE THREAD

**Issue by shyamean4151** [pantasystem/MisskeyAndroidClient#76]
hello，kinoshita0623
数日前にmilkteaでログインできました。最近、milkteaでサーバーエラーが表示され、ログインできません。この前にドメイン名とサーバーを変更しました。
特にミルクティーを使いたいのですが、解決策はありますか？
都合がよければ、中国語の翻訳を投稿できますか？

**Comment by Kinoshita0623** [comment]
「アカウントを追加」から新たなサーバーで認証することで設定は引き継がれませんが、引き続きご利用できます。
設定が引き継がれない理由として、MilkteaはリモートのアカウントId&ドメイン名またはuserName&ドメイン名でアカウントを識別し、そのアカウントと設定情報を紐づけしているため、引き継がれません。
中国語への対応ですが、中国語は種類（簡体字・繁体字）が多く現段階ではアプリケーションの変更、修正が多く多忙なため、現時点では対応は難しいです。

**Comment by shyamean4151** [comment]
できれば、ソフトを簡体字中国語と繁体字中国語に翻訳してもいいです。

**Comment by Kinoshita0623** [comment]
簡体字中国語と繁体字中国語に対応すればいいのですか？

**Comment by shyamean4151** [comment]
あなたが望むなら私は提供することができます。
